sudo: false
script:
  - latexmk -silent -pdf masterthesis.tex
  - latexmk -silent -pdf presentation.tex
  #- chktex -q -n 6 *.tex **/*.tex 2>/dev/null | tee lint.out
  #- test ! -s lint.out
addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - chktex
      - latexmk

