sudo: false
script:
  - latexmk -pdf masterthesis.tex
  - latexmk -pdf presentation.tex
  #- chktex -q -n 6 *.tex **/*.tex 2>/dev/null | tee lint.out
  #- test ! -s lint.out
addons:
  apt:
    sources:
      - sourceline: 'ppa:texlive-backports/ppa'
    packages:
      - texlive-full
      - chktex
      - latexmk

