install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  - sudo apt-get install chktex latexmk

script:
  - latexmk masterthesis
  - latexmk presentation
  #- chktex -q -n 6 *.tex **/*.tex 2>/dev/null | tee lint.out
  #- test ! -s lint.out
