sudo: false

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-science
      - texlive-bibtex-extra
      - latexmk

script:
  - latexmk masterthesis
  - latexmk presentation
